import "dotenv/config"
// TODO: https://github.com/ploskovytskyy/next-app-router-trpc-drizzle-planetscale-edge/blob/main/src/env.mjs
// import { sql } from "drizzle-orm"
// import { readMigrationFiles } from "drizzle-orm/migrator"
import { drizzle } from "drizzle-orm/postgres-js"
import { migrate } from "drizzle-orm/postgres-js/migrator"
import postgres from "postgres"

const migrationConnection = postgres(process.env.DATABASE_URL!, { max: 1 })
const queryConnection = postgres(process.env.DATABASE_URL!)

export const db = drizzle(queryConnection)
export const dbMigration = drizzle(migrationConnection, { logger: true })

// const customMigrations = async () => {
//   const migrationsFolder = path.join(__dirname, ".", "sql")

//   console.log(`Running custom migrations from ${migrationsFolder}...`)

//   const migrations = readMigrationFiles({ migrationsFolder })

//   await db.transaction(async (tx) => {
//     for await (const migration of migrations) {
//       for (const stmt of migration.sql) {
//         await tx.execute(sql.raw(stmt))
//       }
//     }
//   })

//   console.log("Finished running custom migrations")
// }

const main = async () => {
  console.log("Running migrations")

  // await customMigrations()

  console.log("Running autogenerated migrations")

  await migrate(dbMigration, {
    migrationsFolder: "lib/db/migrations",
    migrationsTable: "drizzle_migrations",
  })

  console.log("Migrated successfully")

  await migrationConnection.end()

  process.exit(0)
}

main().catch((e) => {
  console.error("Migration failed")
  console.error(e)
  process.exit(1)
})
